development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%=ENV['REDIS_URL']%>
  # url: <%= ENV['redis://rediscloud:HJ2V7621lEUMMrhNNbPVwmKVRvracr8R@redis-17478.c6.eu-west-1-1.ec2.cloud.redislabs.com:17478'] %>
  channel_prefix: ronpa_production
